import type { ChallengeSpec } from './types';

export const CHALLENGES: ChallengeSpec[] = [
  {
    id: 'ice-tower',
    name: 'Frozen Foundation',
    blurb: 'Stack high on slippery ice. Friction is your enemy.',
    platform: 'ice',
    shapesAllowed: ['I', 'O', 'L', 'J'],
    goalHeight: 280,
    goalScore: 350,
    wind: 0,
    bossTag: '',
  },
  {
    id: 'storm',
    name: 'Stormcaller',
    blurb: 'Heavy winds threaten to topple your tower.',
    platform: 'wood',
    shapesAllowed: ['I', 'O', 'L', 'J', 'T'],
    goalHeight: 320,
    goalScore: 500,
    wind: 0.55,
    bossTag: 'gales',
  },
  {
    id: 'L-only',
    name: 'L-shaped Labyrinth',
    blurb: 'Only L and J pieces. Plan carefully.',
    platform: 'wood',
    shapesAllowed: ['L', 'J'],
    goalHeight: 240,
    goalScore: 300,
    wind: 0,
  },
  {
    id: 'bouncy',
    name: 'Bounce House',
    blurb: 'Bouncy platform. Land softly!',
    platform: 'bouncy',
    shapesAllowed: ['O', 'I', 'T'],
    goalHeight: 220,
    goalScore: 320,
    wind: 0,
  },
  {
    id: 'quake',
    name: 'Quakemaster',
    blurb: 'The platform shakes. Time your drops.',
    platform: 'wood',
    shapesAllowed: ['I', 'O', 'L', 'J', 'T', 'S', 'Z'],
    goalHeight: 360,
    goalScore: 600,
    wind: 0.2,
    bossTag: 'quake',
  },
  {
    id: 'magnet',
    name: 'Magnet Mayhem',
    blurb: 'A magnetic platform pulls every block off-center.',
    platform: 'magnetic',
    shapesAllowed: ['O', 'I', 'L', 'J', 'T'],
    goalHeight: 300,
    goalScore: 480,
    wind: 0,
  },
  {
    id: 'zigzag',
    name: 'Zigzag Trial',
    blurb: 'Only S and Z pieces. Awkward and unforgiving.',
    platform: 'wood',
    shapesAllowed: ['S', 'Z'],
    goalHeight: 200,
    goalScore: 420,
    wind: 0.15,
    bossTag: 'zigzag',
  },
  {
    id: 'fragile-tower',
    name: 'Glass Cathedral',
    blurb: 'Fragile platform. Stack with grace.',
    platform: 'fragile',
    shapesAllowed: ['I', 'O', 'L', 'J'],
    goalHeight: 260,
    goalScore: 340,
    wind: 0,
  },
  {
    id: 'titan',
    name: 'Boss: The Titan',
    blurb: 'All seven pieces, shaking ground, gusting wind. The ultimate challenge.',
    platform: 'fragile',
    shapesAllowed: ['I', 'O', 'T', 'S', 'Z', 'L', 'J'],
    goalHeight: 400,
    goalScore: 800,
    wind: 0.5,
    bossTag: 'titan',
  },
];
